// <auto-generated />
namespace Dojo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class anotationsmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anotationsmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202007271201195_anotations-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
