// <auto-generated />
namespace Dojo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class monosamuraiarmeuni : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(monosamuraiarmeuni));
        
        string IMigrationMetadata.Id
        {
            get { return "202007281531469_mono-samurai-arme-uni"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
